### ISSUE TITLE
[REQUEST] GZ/Zandronum RT next?

### ISSUE THREAD

**Issue by Matsilagi** [sultim-t/prboom-plus-rt#10]
Having a basic engine is cool and all but, seeing that GZDoom has lots of renderer options including Vulkan, and that Zandro is based on GZDoom (Uses OpenGL tho), it would be cool to have a more moddable engine aswell.

Not sure how much other mods would weigh on the equation, but im pretty sure its still miles less than HL RT or even SSam.

**Comment by losspik** [comment]
I second this trying to get a couple mods to work with it namely hd sprites but a direct GZdoom or Zandro would be the holy grail

**Comment by arrowgent** [comment]
RTGL could be built as a plugin shader.  possibly.  maybe nothing more than a .pk3 added
unsure if zdoom source would need to be involved for a custom binary:  possibility to make a standalone .pk3 plugin

**Comment by Matsilagi** [comment]
> RTGL could be built as a plugin shader. possibly. maybe nothing more than a .pk3 added unsure if zdoom source would need to be involved for a custom binary: possibility to make a standalone .pk3 plugin

Naah, it can't. It requires more in-engine changes than any shader could do even with ZScript and GLSL. Its better to make it a full-blown renderer.

**Comment by arrowgent** [comment]
given that RTGL1 is a standalone library
you would just need to hook the required gzdoom features in the code
**_i know, i say "its simple" its a bit of a hyperbolic statement._**  

but i would say converting from prboom-plus to gzdoom is entirely possible, with enough work.

**Comment by Matsilagi** [comment]
Again, yes, it IS a standalone library, but it doesn't magically do all the work. You still need to properly prepare the renderer for that.

Anyways, only time will tell if that will or will not happen.

**Comment by EliteCombineSoldier** [comment]
I have talked with sultim about his engine choice he said this

"Gzdoom was too complicated to me, it was my first try to bring RT to Doom, but i gave up on it"

**Comment by sultim-t** [comment]
@EliteCombineSoldier What I wanted to say is that GZDoom has the abstractions that were tricky to understand: what is the sequence of the graphics function calls, how the objects interact... So, with the limited development time (2 months), after 1-2 weeks with GZDoom I gave up and started looking into the simpler engine which was the PrBoom :)

**Comment by Matsilagi** [comment]
> @EliteCombineSoldier What I wanted to say is that GZDoom has the abstractions that were tricky to understand: what is the sequence of the graphics function calls, how the objects interact... So, with the limited development time (2 months), after 1-2 weeks with GZDoom I gave up and started looking into the simpler engine which was the PrBoom :)

Yeah, i could've imagined, seeing how GZDoom account for lots of modifications.
Ohwell, if you ever feel not in a hurry and feel like retrying, i would be really glad to see atleast Zandronum so i could play Multiplayer with those visuals.

Congrats on the efforts still! Really good to see classics like those revitalized, would love to see what you could do to Quake 3 and Doom 3. Just like Carmack intended.
