### ISSUE TITLE
 RTX 2060 and ERROR RT:3

### ISSUE THREAD

**Issue by artrag** [sultim-t/prboom-plus-rt#11]
I've a  RTX 2060, but the game does not start. 
Just after the initial screen and the tart of the music I get in a small window a message "RT: 3" with a "ok" button to press. 
I do not get any menu, noting to interact with. If I press ok the game cloeses its windows silently.

**Comment by blackletum** [comment]
which doom wad are you using, out of curiousity's sake?

I'm using the wad that came with Doom3 BFG and it gave me a warning that it might not be compatible. I get through E1M1 and then get the same error as you. 

I am running an RTX 3070.

**Comment by artrag** [comment]
I've changed WAD file and now it works, thanks
