### ISSUE TITLE
[version] upstream parity versioning

### ISSUE THREAD

**Issue by arrowgent** [sultim-t/prboom-plus-rt#15]
it would be preferable if prboom-plus was noted which version is being used

prboom-plus 2.6.2, updated SVN version (2022-02-11)

also "rt v1.0.0" is a bit of a misnomer,  first release without any alpha testing.  
id prefer "prboom-plus-rt_2.6.2" a,b,c,d,etc to more closely relation this with the upstream versioning

currently: using version 2.6.1um (16 Aug 2021)

https://github.com/sultim-t/prboom-plus-rt/blob/f7fd74ed01a900476a004c8635c9b3e1c349241c/prboom2/NEWS#L1
https://github.com/sultim-t/prboom-plus-rt/blob/f7fd74ed01a900476a004c8635c9b3e1c349241c/prboom2/README#L1
https://github.com/sultim-t/prboom-plus-rt/blob/f7fd74ed01a900476a004c8635c9b3e1c349241c/prboom2/CMakeLists.txt#L4

so technically your release could be `prboom-plus-rt_2.6.1a` and `prboom-plus-rt_2.6.1b`
a = v1.0.0
b = v1.0.1

**doesnt have to be! just suggestion to keep parity with the upstream base**

this also helps identify which versions are being used because of upstream patches and fixes
some pretty serious ones related to SDL2
`- fixed Alt+Tabbing on Windows, broken in new SDL2 version`

https://github.com/coelckers/prboom-plus/commit/db29f6f5dd760af82328bb945c738a04b6726ccb

**Comment by sultim-t** [comment]
Yeah, it makes sense, thanks :)
