### ISSUE TITLE
DLSS always unavalable

### ISSUE THREAD

**Issue by franciscusm** [sultim-t/prboom-plus-rt#18]
Hi,

First of all thanks for the incredible MOD!

It works fine on my end except for DLSS that always appears in grey as unavailable, even after copying nvngx_dlss.dll to the installation folder.

Tried in two different computers with latest drivers: desktop with RTX 2070 and laptop with quadro RTX 3000.

Thanks.

**Comment by fairwarning17** [comment]
same issue with a 2080 ti, latest drivers, win 11

**Comment by sultim-t** [comment]
I will keep in mind to add more logging about error reasons -- some code restructuring is required

**Comment by scyto** [comment]
@franciscusm  make sure you have the 14.5MB nvgnx_dlss.dll file - at least one person right clicked the link save and just downloaded the HTML of the files page, not the file...

**Comment by franciscusm** [comment]
lol that was it.

Thanks @scyto
