### ISSUE TITLE
Can't initialize ray tracing engine

### ISSUE THREAD

**Issue by PaciTheOne** [sultim-t/prboom-plus-rt#19]
Sorry in advance if this is a dumb question.

Every time I try to open the .exe it starts by saying "Running "Doom: Ray Traced" for the first time. Ensure that the latest drivers are used." and then "Can't initialize ray tracing engine."
I have the latest nvidia drivers installed and everything. The only thing that I can currently think of as the reason is that I don't have an RTX card, but it doesn't seem like I actually need one.

I'm probably just being **very** stupid right now, but could someone please tell my why this is happening?

**Comment by PaciTheOne** [comment]
> You can check GPU compatibility here: https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=all

Sorry if I'm not supposed to comment on closed issues, but I did. My GPU, the Titan X, is supported. But it still doesn't work for me.

**Comment by BuzzKnightbeer** [comment]
Same problem, GPU is supported according to the list. 3060 Laptop GPU

**Comment by ltomes** [comment]
I have the same problem, same gpu as @BuzzKnightbeer.

**Comment by ltomes** [comment]
@BuzzKnightbeer I resolved my issue.

https://nvidia.custhelp.com/app/answers/detail/a_id/5182

Specifically, I installed Advanced Micro Devices, Inc. - Extension - 30.0.13002.23, before installing that, gpu-z reported the 3060 as not supporting Vulcan (but the AMD iGPU did). After installing that extension, both gpus report supporting Vulkin, and prboom runs as expected.

**Comment by juanputrerasm** [comment]
> @BuzzKnightbeer I resolved my issue.
> 
> https://nvidia.custhelp.com/app/answers/detail/a_id/5182
> 
> Specifically, I installed Advanced Micro Devices, Inc. - Extension - 30.0.13002.23, before installing that, gpu-z reported the 3060 as not supporting Vulcan (but the AMD iGPU did). After installing that extension, both gpus report supporting Vulkin, and prboom runs as expected.

This solution worked for me also. 
Nvidia GeForce RTX 3070 Laptop GPU (v 30.0.15.1215) with AMD Radeon Vega iGPU (v 27.20.14044.4001 OEM)

**Comment by rschitz** [comment]
got the same issue on RTX 3090 with the latest driver

**Comment by MadScientist75** [comment]
> > You can check GPU compatibility here: https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=all
> 
> Sorry if I'm not supposed to comment on closed issues, but I did. My GPU, the Titan X, is supported. But it still doesn't work for me.

I think the issue is that the Pascal card don't support new ray tracing extensions. Specifically VK_KHR_ray_query as shown in this comparison
![image](https://user-images.githubusercontent.com/32380729/162557193-23ba449d-2101-40fb-9169-e43be3d82b95.png)

**Comment by CUTWEST** [comment]
I created an account just to comment. Im having the same issues. 

GTX 1080ti....and judging by the comments majority of the people here are on Pascal hardware which leaves me to believe that this program only worths specifically with RTX cards. If so the author needs to make that clear. Instead of saying this works on nvidia hardware he needs to specific RTX only.

**Comment by ltomes** [comment]
> I created an account just to comment. Im having the same issues.
> 
> GTX 1080ti....and judging by the comments majority of the people here are on Pascal hardware which leaves me to believe that this program only works specifically with RTX cards. If so the author needs to make that clear. Instead of saying this works on nvidia hardware he needs to specify RTX only.


@sultim-t, if you're open to a refactor of the readme into a readme.md file, I can do that on https://github.com/ltomes/prboom-plus-rt/commit/920c55f8ce16f488847b535f0828c7280effe6bb 

I can throw some details in on supported hardware.

**Comment by shizukachan** [comment]
Are you sure it's not just that DLSS is queried and Pascal fails? VK_KHR_ray_query isn't used by the engine.

See https://github.com/sultim-t/RayTracedGL1/pull/12 for issue on similar, non-DLSS-supporting hardware

**Comment by MadScientist75** [comment]
> Are you sure it's not just that DLSS is queried and Pascal fails? VK_KHR_ray_query isn't used by the engine.
> 
> See [sultim-t/RayTracedGL1#12](https://github.com/sultim-t/RayTracedGL1/pull/12) for issue on similar, non-DLSS-supporting hardware

That may be it. I have no idea whether the game uses the extension, that was just a guess. How do you know that it doesn't use the VK_KHR_ray_query?

**Comment by rschitz** [comment]
> got the same issue on RTX 3090 with the latest driver

with the 512.15 version from 03/22/2022 it's running fine, sorry about my previous statement.

**Comment by gitsjd** [comment]
@sultim-t, unless I missed it, perhaps post what Nvidia driver version is required to run this, as many are hitting these ongoing issues, possibly due to incompatible driver versions.

**Comment by shizukachan** [comment]
has anyone tried building without DLSS, eg. -DRG_WITH_NVIDIA_DLSS=OFF? That seems to be one of the many reasons device creation fails. See aforementioned pull request for better kind of fix.

**Comment by Occupied** [comment]
I assume Windows 10 is a requirement, it would be cool to add Windows 7 also.
This article goes a little bit into DirectX 12 and Raytracing on Win7:
https://www.pcgamesn.com/microsoft/directx12-nvidia-ray-tracing-windows-7

**Comment by sultim-t** [comment]
I use Windows 10/11, so no plans for Win7 :). Sorry

**Comment by gitsjd** [comment]
Hopefully the longer we try, someone will figure this issue out.

**Comment by Calinou** [comment]
For those looking to run PrBoom+ RT on a non-raytracing-capable GPU, download the 1.0.7 prerelease and replace RaytracedGL1.dll with the one linked here: https://github.com/sultim-t/prboom-plus-rt/issues/12#issuecomment-1113762046

It will be slow as emulating raytracing functionality using compute shaders is much slower than using dedicated RT units. Stick to a low resolution (ideally 4:3) and consider leaving the framerate cap to the vanilla 35 FPS.

**Comment by gitsjd** [comment]
Can confirm this works on 1070.
