### ISSUE TITLE
[REQUEST] Information on Converting WADs for RT

### ISSUE THREAD

**Issue by Ridge-Racer** [sultim-t/prboom-plus-rt#20]
It's what it says on the tin. It seems pretty intuitive how the material properties are set up (and how you'd set your own). I assume there's also a lot of manual lights that had to be placed and all that stuff is defined in map_metainfo_doom1 but it's a little cryptic just looking at it. Some documentation on the conversion process you went through would be a really big deal I think. It would be a pretty big missed opportunity if people didn't start converting their own doom wads to look nice in your renderer. It doesn't have to be super extensive and as far as value for time spent I think it would be very worth it.

**Comment by Ridge-Racer** [comment]
That is way easier than I thought it would be! Being able to set everything up in game helps a ton. Thank you for getting back to me and I super appreciate all the work you're doing for people who like pretty shiny things :)

**Comment by davefletcher1983** [comment]
I know this is closed but is there a way to change the keys for -rtdevmode? I have a 84 key keyboard and don't have the numberpad.

**Comment by sultim-t** [comment]
Oof, it's hardcoded, sorry :/
Someone can change it in the code and recompile

**Comment by arrowgent** [comment]
x2 you can find the keyboard function in the code and change it

https://github.com/sultim-t/prboom-plus-rt/blob/f7fd74ed01a900476a004c8635c9b3e1c349241c/prboom2/src/m_menu.c#L5648

seen here is PGUP, KP_MINUS, KP_PLUS, KP_MULTIPLY
change to the keys you want (buttons are reported by SDL)

**Comment by davefletcher1983** [comment]
LOL no idea what I am doing but going to see if I can change it up.

**Comment by davefletcher1983** [comment]
Trying to figure out how to build this with the buttons changed and keep getting errors...
