### ISSUE TITLE
[REQUEST] Controller support?

### ISSUE THREAD

**Issue by jrouzies-fr** [sultim-t/prboom-plus-rt#22]
Hello!

Amazing conversion to RayTracing, love it! After Quake we really needed that!

Wondering though if you could add support for (Xbox) gamepad?

Thanks

**Comment by scyto** [comment]
the underlying prboom+ doesn't seem to have controller support, most folks use xpadder or joytokey 
seems unlikely this project would take on that burden of adding support, buy hey, maybe you get lucky :-)
