### ISSUE TITLE
Use GZDoom as a base next time.

### ISSUE THREAD

**Issue by darkhog** [sultim-t/prboom-plus-rt#23]
I really wish it was based on a more popular source port, like GZDoom, so I could run all my favorite wads that don't work with PrBoom. Hopefully GZDoom devs will add raytracing as an option based on this code.

**Comment by lafoxxx92** [comment]
Maybe submit a feature request in this project instead? https://github.com/coelckers/gzdoom/issues
Seems like all the GZDdoom Devs are there...

**Comment by sultim-t** [comment]
I hope some people (not me 🙃) will integrate RT to GZDoom

**Comment by Calinou** [comment]
For reference, see also the discussion in https://github.com/sultim-t/prboom-plus-rt/issues/10.
