### ISSUE TITLE
cannot enable Nvidia DLSS.. it says unsupported

### ISSUE THREAD

**Issue by clyder** [sultim-t/prboom-plus-rt#26]
I cannot enable Nvidia DLSS. I have a 2070RTX. I see it in a supported card list.
I placed both the music folder and nvngx_dlss.dll in the same folder prboom-plus.exe is.
Graphics drivers are updated, I tried running it as administrator and even tried manualy changing cfg file and rt_dlss property to something other than 0 (tried 1 and 2) and nvidia dlss is always grayed out.
I can use AMD fsr though.
![settings](https://user-images.githubusercontent.com/1040296/161435437-2ee0d834-5bd5-4414-aa14-84a056e87be4.png)
![files](https://user-images.githubusercontent.com/1040296/161435440-d2b5dd08-b68d-46d4-9da3-9e5840dd5759.png)

_Originally posted by @clyder in https://github.com/sultim-t/prboom-plus-rt/issues/13#issuecomment-1086892130_

**Comment by clyder** [comment]
I originaly posted this in this thread:
https://github.com/sultim-t/prboom-plus-rt/issues/13#issuecomment-1086892130

but then saw it was closed... I followed everything (multiple times) and this option is always unsupported.
Yesterday I tried updating prboom+ but the same.

**Comment by MarkFinnigan** [comment]
I'm having the same issue with all the latest drivers on a 3060Ti

**Comment by scyto** [comment]
> I cannot enable Nvidia DLSS. I have a 2070RTX. I see it in a supported card list. I placed both the music folder and nvngx_dlss.dll in the same folder prboom-plus.exe is. Graphics drivers are updated, I tried running it as administrator and even tried manualy changing cfg file and rt_dlss property to something other than 0 (tried 1 and 2) and nvidia dlss is always grayed out. I can use AMD fsr though. ![settings](https://user-images.githubusercontent.com/1040296/161435437-2ee0d834-5bd5-4414-aa14-84a056e87be4.png) ![files](https://user-images.githubusercontent.com/1040296/161435440-d2b5dd08-b68d-46d4-9da3-9e5840dd5759.png)
> 
> _Originally posted by @clyder in [#13 (comment)](https://github.com/sultim-t/prboom-plus-rt/issues/13#issuecomment-1086892130)_

Given the nvgnx_dlss.dll file should be around 14,457 KB I would say your download of that file is borked.

**Comment by clyder** [comment]
@scyto Yes that was it... I just cliked on the link, right click. save linked content.. and given that the link ends with dll I got just the html page with a name  nvngx_dlss.dll.

I downloaded it from the link and it works now. 
Thank you.

**Comment by scyto** [comment]
you are wlecome, have fun!
