### ISSUE TITLE
Newest version trips antivirus

### ISSUE THREAD

**Issue by Doomguy13** [sultim-t/prboom-plus-rt#28]
Obviously could be false positives, but Virustotal flags 8 possibles, all but one related to the prboom-plus.exe. Figured better safe than sorry to mention it, if it's nothing feel free to disregard,

![Untitled1](https://user-images.githubusercontent.com/68921528/162198251-3f0b5400-691e-408f-8fc3-8c0c88da61d9.jpg)
![Untitled2](https://user-images.githubusercontent.com/68921528/162198255-2f1c96dc-645f-4675-8788-e68ddb95657d.jpg)

**Comment by scyto** [comment]
Didn't trip any of mine.  You might want to report it as false positive to those vendors at the top of the list.
(i regularly do that for MS Defender, amazing how quickly they change signatures, not sure if other vendors are as good)

**Comment by arrowgent** [comment]
if the exe is unsigned it can give false positives.
signing a .exe is a costly and troublesome problem


does totalvirus trigger anything with vanilla prboom-plus 2.6.2?

**Comment by Demiath** [comment]
Same here, BitDefender doesn't like the .exe one bit...
![image](https://user-images.githubusercontent.com/103313320/162568090-b3b87122-cf30-495f-a1a9-f89b375dba9a.png)

**Comment by Doomguy13** [comment]
> if the exe is unsigned it can give false positives. signing a .exe is a costly and troublesome problem
> 
> does totalvirus trigger anything with vanilla prboom-plus 2.6.2?

no, the standard prboom-plus file from their github doesn't trigger anything. on top of just wanted to be better safe than sorry, i also know some people have noted before that there are unofficial versions of the prboom-plus port going around that have infected files and that people should stick to getting them from the official sources. wonder if this is just another case of false positives or if our gracious host sultim-t may have grabbed one of those unofficial ones to package with this.

regardless, i took it off my computer for now, as the previous versions don't have this issue.

**Comment by awksie** [comment]
> i also know some people have noted before that there are unofficial versions of the prboom-plus port going around that have infected files and that people should stick to getting them from the official sources. wonder if this is just another case of false positives or if our gracious host sultim-t may have grabbed one of those unofficial ones to package with this.  

That's not how software development works. It's a false positive.

**Comment by Doomguy13** [comment]
> 

ha, fair point. i'll close this on up, seems like i was just being overly cautious.
