### ISSUE TITLE
[REQUEST] Colored Point Lights

### ISSUE THREAD

**Issue by Ridge-Racer** [sultim-t/prboom-plus-rt#30]
In the current build there are a lot of cool emissive textures to play with and I've been having fun messing around with colors. However these emissives don't seem to cast player/entity shadows the way the sector lights do so the effect is kind of limited. A mapper can do a lot to make up for this by placing sector lights in the right places but the white lighting washes out the desired color from the emissives. Being able to set a color for each of these lights (even just by editing map_metainfo) would open up a ton of really cool looking mapping possibilities.

![doom](https://user-images.githubusercontent.com/84192456/162329328-5daf547c-5b0d-49dd-be66-e795ba50c4ca.png)
Just a screen from me messing around. Thank you again for your time.

**Comment by arrowgent** [comment]
per-pixel lighting?

would be nice.

**Comment by Ridge-Racer** [comment]
I was under the impression that since the renderer was path traced it was already resolving the lighting per-pixel. I'm asking for something much simpler than that. Less complicated than having the emissives cast different lights from individual parts of the texture as well (which is it's own sampling problem that I assume wouldn't be trivial to solve). I just want to be able to change the colors of the sector lights that currently exist in order to jerry rig together some cool looking scenes.

**Comment by sultim-t** [comment]
I will try to add such functionality with the instructions on modding

**Comment by Ridge-Racer** [comment]
awesome thank you

**Comment by sultim-t** [comment]
Added with latest 1.0.4 release :)

**Comment by Ridge-Racer** [comment]
just saw this big appreciate you will definitely have fun checking it out
