### ISSUE TITLE
ERORR RUNNING

### ISSUE THREAD

**Issue by mrmedium** [sultim-t/prboom-plus-rt#31]
![Screenshot (141)](https://user-images.githubusercontent.com/85410819/162488748-0862425b-b928-4542-90cc-3d112040a273.png)
when i ran the application this error was shown. plz help!

**Comment by arrowgent** [comment]
do you have a vulkan GPU?
is your GPU Nvidia?
are your drivers updated?

is the game trying to run on your CPU's GPU? intel/amd? "APU"?

**Comment by mrmedium** [comment]
> 

i dont have a graphics card running it on intel hd620

**Comment by sachahjkl** [comment]
You need a gtx 1060 minimum, NVIDIA Only for now. needs to be closed
