### ISSUE TITLE
Some areas are pitch black

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [sultim-t/prboom-plus-rt#32]
The best solution I can think of, to mimic the original "lighting", is to make it so the player actually casts a light, like you're always carrying a light source of some kind, attached to your waist or something…

Anyway, great project!

**Comment by sultim-t** [comment]
Press `F` to enable a flashlight.
Enable `Classic player light` in the settings to make the flashlight to act not like a spotlight, but a sphere light

**Comment by WeedyWeedSmoker** [comment]
@sultim-t Yeah, I know about the flashlight… I think a more "permanent" way to reproduce the way "lighting" works in the original could be appreciable!

Thanks for your reply
