### ISSUE TITLE
my gpu is not supported yet?

### ISSUE THREAD

**Issue by DOOMMARINE117** [sultim-t/prboom-plus-rt#34]
mine is a nvidia geforce gtx 1050 ti. will that eventually get supported?

**Comment by josuemf** [comment]
technically, never, because it doesn't have any kind of ray tracing support, the bare minimum is  a 1060 and it will run poorly.

https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=all

**Comment by DOOMMARINE117** [comment]
i see, thanks.
