### ISSUE TITLE
CRT look on ReShade? (delete this if not allowed)

### ISSUE THREAD

**Issue by justinjanitzek** [sultim-t/prboom-plus-rt#35]
Sorry, I didn't know where to ask this but I'll just try my luck.

I just tried this out! Excellent RT mod indeed! I was wondering if anyone here tried it with the 320x200 CRT resolution setting! The CRT look on this one is amazing! And I would to replicate that look on ReShade if anyone knows how!

**Comment by NO0bMaster69** [comment]
I found [this reshade preset](https://github.com/sultim-t/prboom-plus-rt/files/8484392/reshadeCRT.zip) that added a crt effect for a game called Bloodstained: Curse of the Moon that I can send. It is configured for my 2560x1440 monitor and if you play at a different resolution you'll need to change the `Resolution=10.000000` line (under the [CRT.fx] heading), replacing 10.000000 with your monitor's horizontal resolution divided by 256 (ex. for a 1920x1080 monitor, it is 1920/256 = 7.500000)
