### ISSUE TITLE
RTX A5000 GPU no DLSS

### ISSUE THREAD

**Issue by nebadon2025** [sultim-t/prboom-plus-rt#45]
I have the "NVIDIA RTX / Quadro Desktop and Notebook Driver Release 510" driver installed and DLSS does not seem to work
[DxDiag.txt](https://github.com/sultim-t/prboom-plus-rt/files/8467881/DxDiag.txt)
.

**Comment by awksie** [comment]
Did you properly extract the DLSS library file (`nvngx_dlss.dll`) to the game folder?

**Comment by drakenabarion** [comment]
I am trying to use DLSS on an RTX3080, and I place "nvngx_dlss.dll" beside the game executable, where I dropped the doom.wad. DLSS is not listed on graphics settings. Could I have the wrong version? I've tried a few.

**Comment by awksie** [comment]
No particular version of the DLL is required; you can even swap out the DLL
version on retail games and it works just fine in practically all cases. I
couldn't even begin to guess why it's not working; try renaming your config
file and starting over from a fresh config maybe?

**Comment by drakenabarion** [comment]
Yeah its very strange. The option for DLSS seems to not exist at all in version 1.0.5 - maybe its only in older versions? I wonder if changing the settings in the cfg could make any difference.

**Comment by nebadon2025** [comment]
ok so sorry I have been busy with a big render project and have not had a chance to look at this again until now, so I updated my drivers and copied over the latest dll i could find, seemed to be many copies on my machine and instead of just grabbing first one in search results I grabbed the one with newest date, also since last test I have installed the Geforce Experience app, no idea if this made an impact but i figured I should also mention that I did this as well.  Anyway it is working now, thanks for the the feedback!
