### ISSUE TITLE
Lost Souls and some other objects don't emit light but should.

### ISSUE THREAD

**Issue by Pete-Lawrence** [sultim-t/prboom-plus-rt#46]
Objects I believe should emit light but currently don't.

Lost Soul. (Currently only emits light when charging).
Soulsphere.
Invulnerability Sphere.
Partial Invisibility Sphere.

**Comment by sultim-t** [comment]
It was intentional for lost souls to emit light only when they charge 
Flashing light source on pickups would increase the noise, it's an artifact of my poor denoiser :/

**Comment by Pete-Lawrence** [comment]
I never said anything about them flashing though. And it's super weird for lost souls to not constantly give out light considering they are on fire.
