### ISSUE TITLE
Norton detects viruses

### ISSUE THREAD

**Issue by sadmadbob** [sultim-t/prboom-plus-rt#50]
Norton(an antimalware software) has been detecting prboom rt(AMD nodlss build) as a virus. the specific threats that Norton said are as follows: "WS.Reputation.1" and "SONAR.dropper". the files that Norton removed are RayTracedGL1.dll and prboom-plus.exe. I'm not sure whether Norton is correct or not. Norton is well known for detecting files that are not malware, and I'm just confused whether this is a virus or not.

**Comment by NO0bMaster69** [comment]
It's a false positive. See issue #49
