### ISSUE TITLE
Not GZDOOM

### ISSUE THREAD

**Issue by Thedeadmemelord** [sultim-t/prboom-plus-rt#51]
While playing with this mod i realised a small engine-related bug: The engine isn't GZDOOM

**Comment by NO0bMaster69** [comment]
This has already been addressed.

> What I wanted to say is that GZDoom has the abstractions that were tricky to understand: what is the sequence of the graphics function calls, how the objects interact... So, with the limited development time (2 months), after 1-2 weeks with GZDoom I gave up and started looking into the simpler engine which was the PrBoom :)

_Originally posted by @sultim-t in https://github.com/sultim-t/prboom-plus-rt/issues/10#issuecomment-1086795823_
