### ISSUE TITLE
Prboom-Plus-RT not working on Vega RX 10.

### ISSUE THREAD

**Issue by sadmadbob** [sultim-t/prboom-plus-rt#53]
I have a Vega 10 RX, which is a integrated GPU. I am having an issue where PrBoom-plus-rt "Can't initialize ray tracing engine: RG_CANT_FIND_PHYSICAL_DEVICE".

**Comment by kd-11** [comment]
RX Vega is from before raytracing was supported on any GPUs.

**Comment by sadmadbob** [comment]
oh
