### ISSUE TITLE
still stalling on start up on 1.04 with upscale and without upscale

### ISSUE THREAD

**Issue by gunther6000** [sultim-t/prboom-plus-rt#56]
https://user-images.githubusercontent.com/55515815/163729248-20362bfc-0b92-432c-a9bd-f005f2f51c68.mp4

**Comment by NO0bMaster69** [comment]
This is caused by the glitch recorded in issue #38.  The demo on the title screen playing through the level triggers the game to crash because of it.

**Comment by gunther6000** [comment]
1.05 fixed it thanks
