### ISSUE TITLE
DLSS not working

### ISSUE THREAD

**Issue by Harry101UK** [sultim-t/prboom-plus-rt#61]
Downloaded the nvngx_dlss.dll (2.4.0 github one) and put it in the prboom-rt-1.0.5 folder next to the .exe, but have no DLSS menu options available.

2080 Super, latest Nvidia drivers.
![nvdll](https://user-images.githubusercontent.com/103963927/163870947-9418a917-93f9-480a-997a-2ffbde83fba6.jpg)
![ndllnope](https://user-images.githubusercontent.com/103963927/163871045-f56eb238-d7fd-461b-8bcc-48355f29a8c1.jpg)

**Comment by sultim-t** [comment]
Oh, yeah, upscaling techniques are removed for now 🙃
