### ISSUE TITLE
PrBoom: Ray Traced 1.0.5 won't launch

### ISSUE THREAD

**Issue by TuffC** [sultim-t/prboom-plus-rt#66]
I downloaded the zip, extracted it, placed the doom.wad file in the extracted folder, tired to launch the application "prboom-plus" and received the following pop up: "Running 'Doom: Ray Traced' for the first time. Ensure that the latest drivers are used." I hit ok and receive another pop up:"I_SignalHandler: Exiting on signal: signal 11". My video card is a NVIDIA GeForce GTX 1060 with Max-Q Design and my drivers version is 512.15 (up-to-date). Can anyone help as I would really like to play this.

**Comment by German-S** [comment]
This is a very known issue, there is a thread below where people try to do anything to get it to run on a GTX 1060/1070/1080 and everyone gets a signal 11 error.
And technically, these devices support VK_KHR_ray_tracing_pipeline, which is necessary for RTX to work in this case.
The author cannot find a solution, version 1.0.5 has already been released, but this issue has not been resolved.

**Comment by TuffC** [comment]
Not fixed with 1.0.5 for GTX 1060, but will close as this is a known issue.
