### ISSUE TITLE
dosent work DLSS with DOOMRT1.0.7 on RTX 3080 

### ISSUE THREAD

**Issue by Aaronsitoo** [sultim-t/prboom-plus-rt#77]
Hi! im played with the version of 1.0.2 DoomRT. All works. But in 1.0.7 de DLSS "seems unvailiable" I dont know why. Im updated the Drivers and replace DLSS archives last version "2.4" i guess is bug of the new version or something like that...

**Comment by davefletcher1983** [comment]
![image](https://user-images.githubusercontent.com/102483264/165594278-ee3b4c44-cabf-43fd-9719-7187875dd7af.png)
Did you follow these instructions? You have to replace the RTGI .dll file

**Comment by Aaronsitoo** [comment]
Didn't work. I will try reinstalling all.

**Comment by Aaronsitoo** [comment]
all right, im only needed reinstall all and then the game works.
